### ISSUE TITLE
As a user, when performing money conversions, I would like to convert to, from, and between major cryptocurrecies 

### ISSUE THREAD

**Issue by 0matleb2** [jusleg/simple-calculator-FAMINGO#108]
**Story Points: 5**

**Risk**: Low
Justification: This is a feature consists of adding in a new view and activity which is quite trivial.
**Priority**: 2
Justification: This is one among other features to be added in this sprint

It should:
* Be responsive
* Use the overall application theme
* have a button in the action bar of the main activity
* have tests

## Description
When performing money conversions, the app should also allow for a selection of major cryptocurrencies, and perform conversion from fiat to crypto, crypto to fiat, and crypto to crypto, using up-to-date conversion rates. The app supports conversion between Bitcoin, Ethereum and Litecoin and from these coins to USD.

## Mockup
![image](https://user-images.githubusercontent.com/14710011/38772413-029bf746-4004-11e8-89da-af5471a6a118.png)

## Acceptance Test

| Test Reference | Test Date | Tester | Test Steps | Expected Result | Actual Result |
|----------------|-----------|--------|------------|-----------------|---------------|
| 1              | 4/14/2018 | Brian Vo | 1) Click cryptocurrency sign menu option 2) Click: '1', '2', '3', '.', '9', '5' in that order | '123.950000' should be displayed | 123.95000 is displayed. Test passed |
| 2              | 4/14/2018 | Brian Vo | 1) Click cryptocurrency sign menu option 2) Click: '1', '2', '3', '.', '9', '5' in that order 3) Press backspace | '123.900000' should be displayed | 123.90000 is displayed. Test passed |
| 3              | 4/14/2018 | Brian Vo | 1) Click cryptocurrency sign menu 2) Scroll to convert from Bitcoin to Ethereum 3) Press '1' 4) Press Convert  | '16.385204' should be displayed | '16.385204' is displayed . Test passed|
| 4              | 4/14/2018 | Brian Vo | 1) Click cryptocurrency sign menu 2) Scroll to convert from Ripple to Litecoin 3) Press '1' 4) Press Convert  | '0.005109' should be displayed | '0.005109' is displayed . Test passed|
| 5              | 4/14/2018 | Brian Vo | 1) Click cryptocurrency sign menu 2) Scroll to convert from USD to USD 3) Press '1' 4) Press Convert  | '1.000000' should be displayed | '1.000000' is displayed . Test passed|

# Tasks
- [x] **New view for cryptocurrency conversion feature** - 3 Ideal hour(s) #130 
- [x] **Backend for cryptocurrency conversion** - 4 Ideal hour(s) #131
- [x] **Tests for cryptocurrency conversion feature** - 2 Ideal Hour(s) #132
