### ISSUE TITLE
As a user, I would like a new view for bitwise calculations

### ISSUE THREAD

**Issue by todd829** [jusleg/simple-calculator-FAMINGO#143]
**Story Points: 8**

Risk: MEDIUM

Priority: MEDIUM

## Description

Users should have the ability to input binary, octal and decimal numbers to perform bitwise operations such as AND, OR and XOR in a new designated view.

## Mockup
See #142 

## Acceptance Test

| Test Reference | Test Date | Tester | Test Steps | Expected Result | Actual Result |
|----------------|-----------|--------|------------|-----------------|---------------|
| 1              |           |        |            |                 |               |
| 2              |           |        |            |                 |               |
| 3              |           |        |            |                 |               |
| 4              |           |        |            |                 |               |
| 5              |           |        |            |                 |               |

# Tasks

- [ ] **View/GUI** - *3* Ideal hour(s) - *Task #146*
- [ ] **Backend Implementation** - *5* Ideal hour(s) - *Task #147*
- [ ] **Tests** - *4* Ideal Hour(s) - *Task #148*
