### ISSUE TITLE
Complete Release Summary

### ISSUE THREAD

**Issue by todd829** [jusleg/simple-calculator-FAMINGO#19]
Complete every section of the _Simple Calculator Release 1 Report_ document in the google drive:
- [x] Mobile App Summary
- [x] Velocity
- [x] Plan for next release
- [x] Overall Architecture and Class Diagrams #17
- [x] Infrastructure
- [x] Code
- [x] Testing and Continuous Integration

**Hour Estimation** : 4 hours
