### ISSUE TITLE
[EPIC] Android Wear

### ISSUE THREAD

**Issue by almiche** [jusleg/simple-calculator-FAMINGO#40]
## Description

An android wear application that contains some of the basic functionality of our phone application.

## User Stories

- [x] As a user, I would like a watch UI **(8 Story Points)** - #91 
- [x] As a user, I would like to have a separate view to perform basic arithmetic (+,-,*,/) on my Wear Device **(8 Story Points)** - #95

**Story points: 16**

## Optional Stories
- [ ] As a user, I would like a consistent theme across all my devices **(1 Story Points)** - #96
- [ ] As a user, I would like to shake my watch to erase the current fields. **(3 Story Points)** - #97

**Story points: 5**
