### ISSUE TITLE
As a user, I would like to convert between different currencies. 

### ISSUE THREAD

**Issue by 0matleb2** [jusleg/simple-calculator-FAMINGO#42]
**Story Point: 5**

Risk: Low
Priority: MEDIUM

The application will allow the conversion of different real-time currencies by leveraging an API.

The feature will be implemented using a popup modal in the 'money' view.

## Mockup

![alt text](https://i.imgur.com/S5owZWC.jpg)

## Acceptance Test

| Test Reference | Test Date | Tester | Test Steps                                                                                                                                                                                             | Expected Result             | Actual Result |
|----------------|-----------|--------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------|---------------|
| 1              | 3/19/2018          | Justin Leger      | 1) Confirm '0.00' is displayed 2) Click currency button. 3) Convert from any currency to another                                                                                                       | '0.00' should be displayed  | 0.00 is displayed. Test passed             |
| 2              | 3/19/2018          | Justin Leger       | 1) Click '2', '0' in that order 2) Click currency button 3) Select 'CAD' under from list 4) Select 'USD' under to list 5) Click 'Convert' 6) Use Google or service of your choice to confirm new value | Google conversion value: 15.29  | '15.29' is displayed. Test passed              |
| 3              | 3/19/2018          | Justin Leger       | 1) Repeat steps 1-5 from test Ref. 2 2) Click currency button 3) Select 'USD' under from list 4) Select 'CAD' under to list 5) Click 'Convert'                                                         | '20.00' should be displayed | '20.00' is displayed. Test passed             |

# Tasks

- [x] **Unit Tests** - 2 Ideal Hour(s) #65 
- [x] **Android Conversion View/GUI** - 1 Ideal Hour(s) #66 
- [x] **Android Backend Implementation** - 4 Ideal Hour(s) #67
