### ISSUE TITLE
As a user, I would like convert between different physical units

### ISSUE THREAD

**Issue by 0matleb2** [jusleg/simple-calculator-FAMINGO#43]
**Story Points: 8**

Risk: LOW

Priority: MEDIUM

## Description
The app should provide a calculator interface whereby the user can perform conversion between all compatible mechanical quantities.

The new view should be able to convert between the following units.

### Weight
* Grams (g)
* Kilograms (kg)
* Ounces (oz)
* Pounds (lb)

### Length
* Centimeters (cm)
* Meters (m)
* Inches (in)
* Feet (gt)

### Volume
* Millilitres (ml)
* Liters (l)
* Quart (qt)
* Gallon (gl)

## Mockups

![Mockup image](https://i.imgur.com/1gtkq2V.jpg)
*Image describing the PR*

## Acceptance Test

| Test Reference | Test Date | Tester | Test Steps | Expected Result | Result |
|----------------|-----------|--------|------------|-----------------|---------------|
| 1              |13/04/2018 | Kevin Zhang | 1. Open the conversion view 2. Press 1, 0, 0       |      "100" should be displayed |PASS|
| 2              |13/04/2018 | Kevin Zhang | 1. Repeat steps in Ref. 1 2. Click Weight 3. Select FROM: g 4. Select TO: kg 5. Click 'Convert' |      "1.0" should be displayed |PASS|
| 3              |13/04/2018 | Kevin Zhang | 1. Repeat steps in Ref. 1 2. Click Length 3. Select FROM: m 4. Select TO: cm 5. Click 'Convert'  |      "100000.0" should be displayed |PASS|
| 4              |13/04/2018 | Kevin Zhang | 1. Repeat steps in Ref. 1 2. Click Volume 3. Select FROM: Ml 4. Select TO: L 5. Click 'Convert' |      "0.1" should be displayed |PASS|

# Tasks

- [ ] **View/GUI** - *3* Ideal hour(s) *TASK #134*
- [ ] **Backend Implementation** - *4.5* Ideal hour(s) *TASK #135 *
- [ ] **Tests** - *2* Ideal Hour(s) *TASK #136 *
