### ISSUE TITLE
As a user, I would like the ability to calculate the taxes based off my location

### ISSUE THREAD

**Issue by izconcept** [jusleg/simple-calculator-FAMINGO#51]
**Story Points: 5**

Risk: HIGH (deals with GPS and adding new permissions)
Priority: HIGH

Based off your location, the application will automatically determine the sales tax rate and apply the tax to the current calculator sum.

## Mockup

![alt text](https://i.imgur.com/jJdvGh5.jpg)

## Acceptance Test

| Test Reference | Test Date | Tester | Test Steps                                                                                                                                                 | Expected Result              | Actual Result |
|----------------|-----------|--------|------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------|---------------|
| 1              |3/19/2018|Brian| 1) Confirm you are in Quebec 2) Confirm that Location Services is enabled 3) Confirm that permissions for the app to access Location Services is allowed 4) Click '1', '0', '0' in that order 5) Click 'Taxes' button                                                                  | '114.98' should be displayed | '114.98' is displayed. Test passed.|
| 2              |3/19/2018|Brian| 1) Confirm that Location Services has been disabled 2) Click '1', '0', '0' in that order 3) Click 'Taxes' button 4) Select 'Quebec' from the dialog | '114.98' should be displayed |'114.98' is displayed. Test passed.|
| 3              |3/19/2018|Brian| 1) Open the app on smartphone or emulator 2) Confirm '0.00' is displayed 3) Click tax button. Select any province if prompted (if location service is disabled)                                          | '0.00' should be displayed   |'0.00' is displayed. Test passed.|

# Tasks

- [x] **Unit Tests** - 1.5 Ideal hour(s) #62 
- [x] **Android Tax View/GUI** - 1 Ideal hour(s) #63 
- [x] **Android Backend Implementation** - 5 Ideal Hour(s) #64

**Comment by miisaka** [comment]
![device-2018-03-08-022049](https://media.giphy.com/media/B31pc5tjVT9xF2DQuj/giphy.gif)
