### ISSUE TITLE
As a user, I would like a new view that allows me to make calculations involving money

### ISSUE THREAD

**Issue by izconcept** [jusleg/simple-calculator-FAMINGO#52]
A new view where users can handle monetary calculations such as calculating tips and taxes.

## User Stories

**Story Points: 13**
- [x] A view with a custom calculator implementation designed to display money. #57 **5 Story Points**
- [x] Converting from currency to currency. #42 - **5 Story Points**
- [x] Automatically calculating taxes based on geolocation data. #51 - **5 Story Points**
- [x] Automatically calculating tip. #54 - **3 Story Points**
