### ISSUE TITLE
As a user, I would like the ability to calculate the tip on a tab

### ISSUE THREAD

**Issue by jusleg** [jusleg/simple-calculator-FAMINGO#54]
**Story Point: 3**

Risk: Low
Priority: MEDIUM

Validation: Enter price and select one of the predefined tip values. The amount should be either 15%, 18%, 20% and custom.

# Tasks

- [x] **Unit Tests** - 1 Ideal Hour(s) #59 
- [x] **Android Tip View/GUI** - 1 Ideal Hour(s) #60 
- [x] **Android Backend Implementation** - 2 Ideal Hour(s) #61
