### ISSUE TITLE
User story, epic, and tasks Github issues template

### ISSUE THREAD

**Issue by izconcept** [jusleg/simple-calculator-FAMINGO#83]
Templates are necessary for Github issues. Different types of issues should have different templates.

- [x] User Story Template (.2 Ideal-Hours)
- [x] Epic Template (.2 Ideal-Hours)
- [x] Task Template (.2 Ideal-Hours)

**Comment by izconcept** [comment]
Issue implemented in PR #84
